### PR TITLE
Added melund as a maintainer.

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by pelson** [comment]
Just so that they know what they are being put forwards for, I tend to ping the user in question.

Ping @melund. You name is up! :smile:

**Comment by melund** [comment]
Thanks @pelson

**Comment by pelson** [comment]
Over to you @scopatz. It's your repo.
:+1:

**Comment by scopatz** [comment]
Be that as it may @pelson, I don't seem to have write access :)

**Comment by pelson** [comment]
> Be that as it may @pelson, I don't seem to have write access :)

You don't have the merge button?

**Comment by scopatz** [comment]
Nope: 
screenshot 2016-02-10 at 14 58 47 - display 1

**Comment by pelson** [comment]
Doh!

screen shot 2016-02-10 at 19 58 24

Looks like the magic script needs to update the permissions - you only have read.

**Comment by scopatz** [comment]
Haha! That'll do it!

**Comment by pelson** [comment]
I'm going to try to fix this the right way. Failing that, I'll fix it the quick way in 5 mins.

**Comment by scopatz** [comment]
Sounds good.  No rush from my end.

**Comment by pelson** [comment]
What a disaster! I deleted all of the teams instead... I should call it a day I think! :smile:
Anyway, the change has been made in https://github.com/conda-forge/conda-forge.github.io/pull/24, and in ~5 minutes the conda-forge/xonsh team should have write permission on the xonsh-feedstock.

**Comment by scopatz** [comment]
You deserve to relax, maybe get some sleep @pelson :)

**Pull request merged**
