### PR TITLE
updated v0.5.6

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by melund** [comment]
I am not sure this is ever going to start. Should we try canceling and then restarting the build

**Comment by gforsyth** [comment]
I don't think so -- Travis is showing a 1K backlog of OSX jobs, not sure if we lose our place in the queue if it restarts...

**Comment by gforsyth** [comment]
Although that _was_ two days ago...

**Comment by gforsyth** [comment]
Ahh, although if Travis limits jobs by organization and not by specific repo then we might be stuck in a conda-forge-specific queue.  There are some conda-forge builds for other projects that were opened 2 days ago that have just started building in the last 30 minutes.  I say we wait until end of day and then take another look.

**Comment by melund** [comment]
@gforsyth . That makes sense. Then it would be nice if didn't have to build it again after we clicked merge (to build and upload the packages). Such a feature could save a lot of computer time.

**Comment by melund** [comment]
If Anaconda.org had a feature to upload packages without making them available. And then another command to enable the packages once the merge request was accepted.

**Comment by scopatz** [comment]
OMG it ran!

**Pull request merged**
