### PR TITLE
Add aarch64/ppc64le

### LINKED ISSUE #180: Missing aarch64 package
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I ran into a problem because an aarch64 build was missing:
```
$ docker run --rm -it --platform=linux/arm64 mambaorg/micromamba micromamba install -c conda-forge xonsh
Unable to find image 'mambaorg/micromamba:latest' locally
latest: Pulling from mambaorg/micromamba
3b157c852f27: Pull complete 
bff729fad3e9: Pull complete 
d17ae33047f3: Pull complete 
2b3f809c472b: Pull complete 
4f4fb700ef54: Pull complete 
91c2bb63d39a: Pull complete 
f724f7925bfb: Pull complete 
0c0345c8b49b: Pull complete 
Digest: sha256:6a4f22ac8cb17cfd9c704218e07f21116142fe5fde05b8e0983efc40e5e263da
Status: Downloaded newer image for mambaorg/micromamba:latest

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/linux-aarch64                            5.2MB @   2.9MB/s  1.8s
conda-forge/noarch                                   8.5MB @   2.4MB/s  3.6s
Encountered problems while solving:
  - nothing provides requested xonsh

The environment can't be solved, aborting the operation
```

### Installed packages

```shell
x
```

### Environment info

```shell
x
```

### PR DESCRIPTION
**Pull request by maresb**
Closes #180

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
After some fairly extensive digging, I found https://github.com/conda-forge/conda-forge.github.io/issues/1668 :joy:

**Comment by maresb** [comment]
Converting to draft, and requesting a migration in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3053

**Comment by gforsyth** [comment]
Thanks for raising the migration request @maresb!  You can ping here or on the issue if you hit any roadblocks.

**Comment by maresb** [comment]
superseded by #182

**Pull request closed without merging**
