### PR TITLE
Update xonsh homepage

### PR DESCRIPTION
**Pull request by melund**

### CODE REVIEW

**Comment by scopatz** [comment]
Ahh so important!

**Comment by scopatz** [comment]
Though it looks like appveyor failed again!

**Comment by ocefpaf** [comment]
> Though it looks like appveyor failed again!

Nope. This is just because the PR was merged before AppVeyor finished. (Which is sensible in a change like this. No need to wait for the CIs.)

**Comment by melund** [comment]
Ok. Great. I just discovered one other occurrence of the old web page in the readme file. It was updated automatically when tried to run `conda smithy rerender`. Another PR is incoming.

**Comment by scopatz** [comment]
Ahh ok.  Thanks for the explanation @ocefpaf.

**Pull request merged**
