### PR TITLE
version 0.4.1

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by melund** [comment]
Now the problem is solves from for all except Python 3.4 x64.

**Comment by scopatz** [comment]
Ummhmm - and the problem of super long queues :)

**Comment by melund** [comment]
I reverted back to conda-build 1.20.0. There was still the issue with py34 x64 with conda-build >1.20.0

**Comment by scopatz** [comment]
Should I pull that in here?

**Comment by scopatz** [comment]
Just did :)

**Pull request merged**
