### PR TITLE
v0.4.0 bump

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by melund** [comment]
+1 for moving away from pypi. I wanted to do this for one the previous releases. Anyway, why does it fail for window 3.4 32 bit :(

**Comment by melund** [comment]
Let me try to rerender the feedstock.

**Comment by scopatz** [comment]
@melund OK.  Tell me when to pull pack down.

**Comment by melund** [comment]
Ok. Rerender didn't change anything. @pelson Can you help with the error here. it is failing for AppVeyor on python 3.4 x86 ...The errror meassage comes from here: 
```
https://github.com/xonsh/xonsh/blob/master/setup.py#L154
```

**Comment by melund** [comment]
@scopatz . I think we can still merge the PR despite this. How uses windows x86 anyway :) And we can probably fix later.

**Comment by scopatz** [comment]
Alright, I was thinking something similar @melund.  Do you want to hit the merge button? :)

**Comment by melund** [comment]
No problem :)

**Comment by pelson** [comment]
> Ok. Rerender didn't change anything. @pelson Can you help with the error here

Probably best to ping ```conda-forge/core``` rather than me directly - I'm notoriously hard to contact at this time of the year :smile:. Truth be told, I'm a little out of touch with issues at the moment, @jjhelmus have you seen anything go by recently that may explain?

**Comment by ocefpaf** [comment]
@melund whatever the error was it is now gone. I cannot see the same failure in master after this merge.

**Comment by melund** [comment]
No problem. We will remember to use @conda-forge/core next time. We reverted back to conda-build 1.20.0 that fixed it for us.

**Pull request merged**
