### PR TITLE
xonsh v0.4.6

### PR DESCRIPTION
**Pull request by scopatz**
Merge only after success.

### CODE REVIEW

**Comment by scopatz** [comment]
Any ideas why this breaks @conda-forge-core

**Comment by ocefpaf** [comment]
> Any ideas why this breaks @conda-forge-core

@scopatz update your conda-smithy and rerender your feedstock.

PS: It is @conda-forge/core

**Comment by scopatz** [comment]
How do you rerender?  The instructions on the smithy readme seem incorrect...

**Comment by ocefpaf** [comment]
The command is:

$ conda smithy rerender

from the root directory of the feedstock. I can do that for you tomorrow
morning. (Away from the computer now. )

**Comment by scopatz** [comment]
Ahh thanks!  I was on an old version of the smithy

**Pull request merged**
